services:
  - type: web
    name: compareall-api
    env: node
    buildCommand: npm install && npm run build:backend
    startCommand: npm run start --workspace=@compareall/backend
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
